name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Run unit tests and jacoco coverage
        run: ./gradlew testDebugUnitTest jacocoTestReport --stacktrace

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2.33.0
        with:
          api-level: 26
          script: |
            adb logcat &
            ./gradlew connectedCheck --no-parallel

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4
        with:
          format: jacoco
